# Generated by Django 5.0.2 on 2024-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_aktor_extrainfo_ocena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imdb_pkts',
            new_name='imdb_points',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-fi'), (4, 'Dramat')], null=True),
        ),
    ]
