# Generated by Django 5.0.2 on 2024-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='rezyser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (0, 'Inne'), (4, 'Dramat'), (2, 'Komedia'), (3, 'Sci-fi')], null=True),
        ),
    ]
