# Generated by Django 5.0.2 on 2024-05-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Inne'), (1, 'Horror'), (4, 'Dramat'), (3, 'Sci-fi'), (2, 'Komedia')], null=True),
        ),
    ]
